# Generated by Django 5.1.14 on 2025-11-19 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(choices=[('PRE', 'Prebenjamín'), ('BEM', 'Benjamín'), ('AL', 'Alevín'), ('IN', 'Infantil'), ('CA', 'Cadete'), ('JU', 'Juvenil')], default='AL', max_length=3)),
                ('descripcion', models.TextField(blank=True)),
                ('edad_min', models.IntegerField(default=6)),
                ('edad_max', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salario', models.FloatField(db_column='salario_entrenador', default=400.5)),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrenador', to='club.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrenamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.categoria')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.entrenamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dorsal', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='club.categoria')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='club.entrenador')),
            ],
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='jugadores',
            field=models.ManyToManyField(through='club.Asistencia', to='club.jugador'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador'),
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=None)),
                ('descripcion', models.TextField(max_length=250)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.entrenador')),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.entrenamiento')),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.FloatField()),
                ('pagado', models.BooleanField(default=True)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jugados', models.IntegerField(default=0)),
                ('titular', models.BooleanField(default=False)),
                ('goles', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=150)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('jugadores', models.ManyToManyField(through='club.Participacion', to='club.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='participacion',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.partido'),
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('minutos_jugados', models.PositiveIntegerField(default=0)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.categoria')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.entrenador')),
                ('jugadores', models.ManyToManyField(to='club.jugador')),
            ],
        ),
    ]
