# Generated by Django 5.1.14 on 2025-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='duracion_minutos',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='goles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticasjugador',
            name='minutos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.IntegerField(default=0),
        ),
    ]
